pool:
  vmImage: 'ubuntu-latest'


steps:
- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: $(CONJUR_APPLIANCE_URL)
    conjuraccount: $(CONJUR_ACCOUNT)
    conjurusername: $(CONJUR_AUTHN_LOGIN)
    conjurapikey: $(CONJUR_AUTHN_API_KEY)
    ignoreSsl: true

- bash: |
    echo "$(dbUname)" | base64
    echo "$(dbPwd)" | base64
    ./secrets_echo.sh _$(dbUname)_ _$(dbPwd)_